#!/usr/bin/env bash
# Install the certificate-authority role.
#
# The CA is a directory of key material owned by the ODM service user. This
# script only prepares that directory and its permissions; the root
# certificate itself is created from the console, so the private key is
# generated by the running service and never sits in a shell history.

set -euo pipefail

CA_DIR="/var/lib/odm/ca"
SERVICE_USER="odm"

usage() {
    echo "usage: install-certificate-authority-role.sh [--ca-dir <path>]" >&2
    exit 2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --ca-dir) CA_DIR="${2:?}"; shift 2 ;;
        -h|--help) usage ;;
        *) echo "unknown argument: $1" >&2; usage ;;
    esac
done

[[ $EUID -eq 0 ]] || { echo "must run as root" >&2; exit 1; }
[[ "$CA_DIR" =~ ^/[A-Za-z0-9._/-]{1,255}$ ]] || { echo "invalid --ca-dir" >&2; exit 1; }
id -u "$SERVICE_USER" >/dev/null 2>&1 || { echo "the $SERVICE_USER user does not exist" >&2; exit 1; }

install -d -m 0700 -o "$SERVICE_USER" -g "$SERVICE_USER" "$CA_DIR"
install -d -m 0700 -o "$SERVICE_USER" -g "$SERVICE_USER" /var/lib/odm/tls-staging

cat <<SUMMARY

Certificate authority role installed.

  CA directory  $CA_DIR (0700, owned by $SERVICE_USER)

Add to the ODM secrets file and restart the API:

  ODM_CA_DIR=$CA_DIR

Then open Certificates in the console and create the root certificate.
SUMMARY
