package apply

import (
	"context"
	"fmt"
	"os"
	"strings"

	"odm.example.org/agent/internal/policy"
)

// Regional settings: language, formats, keyboard and time zone.
//
// Four places have to agree for a machine to feel like it is in the country
// it is in. The system locale (/etc/default/locale) is what the login screen
// and every new session start from; the keyboard (/etc/default/keyboard) is
// what the console and GDM use before anyone has a session to say
// otherwise; the desktop reads its own copies of both from dconf, which is
// where they are locked when the policy says people may not change them;
// and the time zone is the kernel's, set through timedatectl so that
// systemd's own clock services agree with it.
//
// Locales have to exist before they can be selected: locale-gen is run for
// the ones the policy names, and only those are added to /etc/locale.gen —
// what an operator generated by hand stays.

const (
	localeDefaultPath  = "/etc/default/locale"
	localeGenPath      = "/etc/locale.gen"
	keyboardPath       = "/etc/default/keyboard"
	dconfRegionalPath  = "/etc/dconf/db/odm.d/12-odm-regional"
	dconfRegionalLocks = "/etc/dconf/db/odm.d/locks/odm-regional"
)

func applyRegional(ctx context.Context, s policy.Settings, env Env) []policy.Result {
	if s.Regional == nil {
		return nil
	}
	r := *s.Regional
	if env.Run == nil {
		return []policy.Result{policy.Skip("regional", "no command runner")}
	}
	var results []policy.Result

	// The locales, generated. /etc/locale.gen is the system's file: ODM's
	// lines live in its own block, and taking the setting away takes the
	// block out without touching what was there before.
	wanted := []string{r.Locale}
	if r.FormatsLocale != "" && r.FormatsLocale != r.Locale {
		wanted = append(wanted, r.FormatsLocale)
	}
	for _, extra := range r.AdditionalLocales {
		if extra != "" && !hasString(wanted, extra) {
			wanted = append(wanted, extra)
		}
	}
	var gen strings.Builder
	for _, locale := range wanted {
		fmt.Fprintf(&gen, "%s UTF-8\n", locale)
	}
	if err := env.ReplaceBlock(localeGenPath, gen.String(), 0o644); err != nil {
		return append(results, policy.Fail("regional:locales", err))
	}
	if _, err := env.Run.Run(ctx, "locale-gen"); err != nil {
		results = append(results, policy.Fail("regional:locales", err))
	}

	// The system default, and the keyboard. Both are the system's own files
	// (the installer wrote them), so ODM's lines go in a block at the end,
	// where a later assignment wins, and leave with the setting rather than
	// taking the file — and the keyboard map — with them.
	formats := r.FormatsLocale
	if formats == "" {
		formats = r.Locale
	}
	defaults := "LANG=" + r.Locale + "\n" +
		"LC_TIME=" + formats + "\n" +
		"LC_NUMERIC=" + formats + "\n" +
		"LC_MONETARY=" + formats + "\n" +
		"LC_PAPER=" + formats + "\n" +
		"LC_MEASUREMENT=" + formats + "\n"
	if err := env.ReplaceBlock(localeDefaultPath, defaults, 0o644); err != nil {
		return append(results, policy.Fail("regional:locale", err))
	}
	keyboard := "XKBLAYOUT=\"" + r.KeyboardLayout + "\"\n" +
		"XKBVARIANT=\"" + r.KeyboardVariant + "\"\n"
	if err := env.ReplaceBlock(keyboardPath, keyboard, 0o644); err != nil {
		return append(results, policy.Fail("regional:keyboard", err))
	}
	// setupcon reads the file for the text console; a failure there is a
	// machine without one, not a failed setting.
	_, _ = env.Run.Run(ctx, "setupcon", "--save-only")

	// The desktop's copies, and their locks.
	if err := env.WriteFile(
		dconfProfilePath, "user-db:user\nsystem-db:odm\n", 0o644, "root", "root",
	); err != nil {
		return append(results, policy.Fail("regional", err))
	}
	source := "('xkb', '" + r.KeyboardLayout
	if r.KeyboardVariant != "" {
		source += "+" + r.KeyboardVariant
	}
	source += "')"
	keyfile := Header +
		"\n[org/gnome/desktop/input-sources]\n" +
		"sources=[" + source + "]\n" +
		"\n[org/gnome/system/locale]\n" +
		"region='" + formats + "'\n"
	if err := env.WriteFile(dconfRegionalPath, keyfile, 0o644, "root", "root"); err != nil {
		return append(results, policy.Fail("regional", err))
	}
	locks := Header
	if !r.AllowUserChange {
		locks += "/org/gnome/desktop/input-sources/sources\n/org/gnome/system/locale/region\n"
	}
	if err := env.WriteFile(dconfRegionalLocks, locks, 0o644, "root", "root"); err != nil {
		return append(results, policy.Fail("regional", err))
	}
	results = append(results, runAll(ctx, env, "regional:desktop", []string{"dconf", "update"}))

	// The time zone. timedatectl keeps /etc/localtime and /etc/timezone in
	// step and tells the clock services; a machine without it (a container)
	// gets the link written directly.
	if current := currentTimezone(env); current != r.Timezone {
		if _, err := env.Run.Run(ctx, "timedatectl", "set-timezone", r.Timezone); err != nil {
			zone := "/usr/share/zoneinfo/" + r.Timezone
			if _, statErr := os.Stat(env.Path(zone)); statErr != nil {
				results = append(results, policy.Fail("regional:timezone",
					fmt.Errorf("%s is not a time zone this machine knows: %w", r.Timezone, err)))
				return results
			}
			_ = os.Remove(env.Path("/etc/localtime"))
			if linkErr := os.Symlink(zone, env.Path("/etc/localtime")); linkErr != nil {
				results = append(results, policy.Fail("regional:timezone", linkErr))
				return results
			}
			_ = os.WriteFile(env.Path("/etc/timezone"), []byte(r.Timezone+"\n"), 0o644)
		}
	}
	results = append(results, policy.Ok("regional"))
	return results
}

// currentTimezone reads what /etc/timezone says, or "" when it says nothing.
func currentTimezone(env Env) string {
	raw, err := os.ReadFile(env.Path("/etc/timezone"))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(raw))
}

func hasString(list []string, value string) bool {
	for _, entry := range list {
		if entry == value {
			return true
		}
	}
	return false
}
