import {
  C,
  Code,
  Details,
  Example,
  Note,
  Quickstart,
  Reference,
  Section,
  Steps,
  Where,
} from "../components";
import type { WikiPageMeta } from "../types";

export const meta: WikiPageMeta = {
  id: "remote-access",
  title: "Remote access",
  section: "Administration",
  summary:
    "WireGuard tunnels, the configurations people connect with, and always-on for managed machines.",
  keywords: ["vpn", "wireguard", "tunnel", "peer", "remote", "home office", "always on"],
};

export function Content() {
  return (
    <>
      <Quickstart>
        <p>
          A tunnel is a remote-access network: an address range for the people and machines that
          connect, and a list of the networks it carries them into. Each peer is a keypair and an
          address, so a configuration can be handed over before the machine ever connects.
        </p>

        <Example title="Create a tunnel">
          <Steps>
            <li>
              <strong>Server Roles</strong> → <strong>Remote access (VPN)</strong> →{" "}
              <strong>Install on a server</strong>.
            </li>
            <li>
              <strong>Remote Access</strong> → <strong>New tunnel</strong> → the server, a name, and
              the address clients dial from outside.
            </li>
            <li>
              A tunnel network that is not one of yours — <C>10.99.0.0/24</C> is a reasonable
              default.
            </li>
            <li>
              Tick the DHCP scopes the tunnel should reach, and give a name server so names resolve
              while connected.
            </li>
          </Steps>
        </Example>

        <Example title="Let a person connect">
          Open the tunnel → <strong>Add a peer</strong> → name it → <strong>Configuration</strong>{" "}
          on its row downloads the file. It works in <C>wg-quick</C>, NetworkManager, and the
          WireGuard app on a phone.
        </Example>

        <Example title="Hold a tunnel up on a machine">
          <Steps>
            <li>
              Add a peer for the machine and choose its computer under{" "}
              <strong>Domain object</strong>.
            </li>
            <li>
              <strong>Group Policy</strong> → <strong>Settings</strong> → <strong>Computer</strong>{" "}
              → <strong>Always-on VPN</strong> → name the tunnel.
            </li>
            <li>
              The machine brings the tunnel up at boot, before anyone signs in, and the person using
              it cannot turn it off.
            </li>
          </Steps>
        </Example>

        <Where>Remote Access, once a server carries the VPN role.</Where>
      </Quickstart>

      <Details>
        <Section title="Where the keys are">
          <p>
            Keys are generated by the control plane, not on a node. A tunnel&rsquo;s private key
            travels only to the machine terminating it; a peer&rsquo;s private key only to that
            peer, either in a downloaded configuration or through policy to the machine it belongs
            to. Every download is recorded in the audit log, and downloading one needs{" "}
            <C>vpn.write</C> rather than <C>vpn.read</C>: handing out a key is closer to creating
            access than to looking at it.
          </p>
        </Section>

        <Section title="Always-on">
          <Reference
            headers={["Part", "What it is"]}
            rows={[
              [
                "The unit",
                <>
                  <C key="a">wg-quick@&lt;tunnel&gt;</C>, enabled, with{" "}
                  <C key="b">Restart=always</C> so a tunnel that drops comes back.
                </>,
              ],
              [
                "The configuration",
                <>
                  <C key="c">/etc/wireguard/&lt;tunnel&gt;.conf</C>, mode 0600 and owned by root, so
                  the person using the machine can neither read the key nor edit it.
                </>,
              ],
              [
                "Refuse to reach those networks until the tunnel is up",
                "Blackhole routes for everything the tunnel carries, added before it connects and removed when it goes down — so a laptop cannot reach them over whatever it is plugged into instead.",
              ],
            ]}
          />
          <Note>
            A machine with no peer on the tunnel is skipped with that reason rather than given a
            configuration that cannot work. Add the peer, choose its computer, and the next refresh
            picks it up.
          </Note>
        </Section>

        <Section title="What has to be open">
          <p>
            The port each tunnel listens on has to reach the server from outside. Nothing in ODM
            opens it at a perimeter firewall, and it will not say so on its own — a tunnel that
            never connects with no error in the console is almost always this.
          </p>
          <Code>{`# on the VPN server, to confirm it is listening
sudo wg show
sudo ss -ulnp | grep 51820`}</Code>
        </Section>

        <Section title="Removing access">
          <Reference
            headers={["Action", "Effect"]}
            rows={[
              ["Remove a peer", "That configuration stops working at the server's next refresh."],
              [
                "Remove the tunnel",
                "Every configuration on it stops working, and the interface goes down.",
              ],
              [
                "A peer whose key was not kept",
                "Cannot be exported again. Remove it and add a new one — the same is true of any system that does not store keys it handed out.",
              ],
            ]}
          />
        </Section>
      </Details>
    </>
  );
}
